module.exports = {
  CODE: {
    SUCCESS: 200,
    NOT_FOUND: 404,
    SERVER_ERROR: 500,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
  },
  RESPONSE_MESSAGES: {
    SUCCESS: {
      SIGN_UP: "Registration successfull.",
      LOG_IN: "You have logged in successfully.",
      LOG_OUT: "You have logged out successfully.",
      PERMISSION_ADDED: "Permission has been added successfully.",
      PERMISSION_DELETED: "Permission has been deleted successfully.",
      PERMISSION: "Permission",
      PERMISSIONS_LIST: "Permissions list",
      PERMISSIONS_UPDATED: "Permissions updated",
      OTP_FOR_RESET_PASSWORD:
        "OTP to reset password has been sent to your email",
      PASSWORD_UPDATED: "Password has been updated successfully",
      NO_RECORD_FOUND: "No record found",

      ROLE_ADDED: "Role has been added successfully.",
      ROLE_DELETED: "Role has been deleted successfully.",
      ROLE: "Role",
      ROLES_LIST: "Roles list",
      ROLES_UPDATED: "Role updated",

      USER_DELETED: "User has been deleted successfully.",
      USER: "User",
      USERS_LIST: "Users list",
      USER_UPDATED: "User updated",

      ITEM: "Item",
      ITEM_LIST: "Item List",
      ITEM_CREATED: "Item has been created successfully",
      ITEM_DELETED: "Item has beed deleted successfully",
      ITEM_UPDATED: "Item has beed updated successfully",

      VENDOR_DELETED: "Vendor has been deleted successfully.",
      VENDOR_ADDED: "Vendor has been added successfully",
      VENDOR_FOUND: "Vendor has been found successfully",
      VENDOR: "Vendor",
      VENDORS_LIST: "Vendor list",
      VENDOR_UPDATED: "Vendor updated",

      ACCOUNT_DELETED: "Account has been deleted successfully.",
      ACCOUNT_ADDED: "Account has been added successfully",
      ACCOUNT_FOUND: "Account has been found successfully",
      ACCOUNT: "Account",
      ACCOUNTS_LIST: "Account list",
      ACCOUNT_UPDATED: "Account updated",
      ATTENDENCE_UPDATED: "Attendece marked successfully",
      LEAVE_COUNT_UPDATED: "Leave updated successfully",
      SALARY_UPDATED: "Salary updated successfully",

      JOB_DELETED: "Job has been deleted successfully.",
      JOB_ADDED: "Job has been added successfully",
      JOB_FOUND: "Job has been found successfully",
      JOB: "Job",
      JOBS_LIST: "Job list",
      JOB_UPDATED: "Job updated",

      VEHICLE_DELETED: "Vehicle has been deleted successfully.",
      VEHICLE_ADDED: "Vehicle has been added successfully",
      VEHICLE_FOUND: "Vehicle has been found successfully",
      VEHICLE: "Vehicle",
      VEHICLES_LIST: "Vehicle list",
      VEHICLE_UPDATED: "Vehicle updated",

      SERVICE_DELETED: "Service has been deleted successfully.",
      SERVICE_ADDED: "Service has been added successfully",
      SERVICE_FOUND: "Service has been found successfully",
      SERVICE: "Service",
      SERVICES_LIST: "Service list",
      SERVICE_UPDATED: "Service updated",
    },
    FAIL: {
      MISSING_PARAMS: "Please send all the required parameters.",
      USER_NOT_FOUND: "User not found",
      INVALID_OTP_EMAIL: "Invalid OTP or Email",
      WRONG_EMAIL_OR_PASSWORD: "You have provided wrong email or password",
      REQUEST_NOT_COMPLETED: "Request not completed, please try again",
      UNAUTHORIZED: "You are unauthorized, please login and try again",
      INVAID_PERMISSIONS: "You are not permissable to perform this action",
      USER_ALREADY_EXITS: "User already Exists",
      WRONG_EMAIL: "You have provided wrong Email Address",

      VENDOR_ALREADY_EXITS: "Vendor already Exists",
      VENDOR_NOT_EXITS: "Vendor not Exists",
      VENDOR_UPDATED_FAIL: "Vendor has not been updated.Try Again!",

      ACCOUNT_ALREADY_EXITS: "Account already Exists",
      ACCOUNT_NOT_EXITS: "Account not Exists",
      ACCOUNT_UPDATED_FAIL: "Account has not been updated.Try Again!",
      ATTENDENCE_UPDATED_FAIL: "Attendence has not been updated.Try Again!",
      SALARY_UPDATED_FAIL: "Salary has not been updated.Try Again!",
      LEAVE_UPDATED_FAIL: "Leave Count has not been updated.Try Again!",
      ACCOUNT_DELETE_FAIL:
        "Account Deletion Failed Try with Correct Credentials",

      JOB_ALREADY_EXITS: "Job already Exists",
      JOB_NOT_EXITS: "Job not Exists",
      JOB_UPDATED_FAIL: "Job has not been updated.Try Again!",
      JOB_DELETE_FAIL: "Job Deletion Failed Try with Correct Credentials",

      VEHICLE_ALREADY_EXITS: "Vehicle already Exists",
      VEHICLE_NOT_EXITS: "Vehicle not Exists",
      VEHICLE_UPDATED_FAIL: "Vehicle has not been updated.Try Again!",
      VEHICLE_DELETE_FAIL:
        "Vehicle Deletion Failed Try with Correct Credentials",

      SERVICE_ALREADY_EXITS: "Service already Exists",
      SERVICE_NOT_EXITS: "Service not Exists",
      SERVICE_UPDATED_FAIL: "Service has not been updated.Try Again!",
    },
    OTHERS: {
      FORGOT_EMAIL_SUBJECT: "FORGOT PASSWORD OTP",
    },
  },
};
